on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Codebase
        uses: actions/checkout@v3
      - run: touch a
      - run: echo GIT_STATUS=$(git status --porcelain) >> "$GITHUB_OUTPUT"
        id: git_status
      - run: echo ${{ steps.git_status.outputs.GIT_STATUS }}
      