on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Codebase
        uses: actions/checkout@v3
      - run: touch a
      - run: GIT_STATUS=$(git status --porcelain) >> "$GITHUB_OUTPUT"
      - run: echo "$GIT_STATUS"
      