on:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Codebase
        uses: actions/checkout@v3
      - run: touch a
      - run: git status --porcelain
        id: status
      - run: "echo status: ${{ steps.status.outputs.stdout }}"
      